version: '3.8'

services:
  postgres1:
    image: postgres:13
    environment:
      POSTGRES_DB: tao_shard_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tao_shard_1"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres2:
    image: postgres:13
    environment:
      POSTGRES_DB: tao_shard_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tao_shard_2"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres3:
    image: postgres:13
    environment:
      POSTGRES_DB: tao_shard_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_3:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tao_shard_3"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_1:
  postgres_data_2:
  postgres_data_3:
