// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

pub type ENTPOST_CONTENT = String;

pub type ENTPOST_MEDIA_URL = String;

pub type ENTPOST_POST_TYPE = String;

pub type ENTPOST_VISIBILITY = String;

//
// ValidationException
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ValidationException {
  pub message: String,
  pub field: Option<String>,
}

impl ValidationException {
  pub fn new<F2>(message: String, field: F2) -> ValidationException where F2: Into<Option<String>> {
    ValidationException {
      message,
      field: field.into(),
    }
  }
}

impl TSerializable for ValidationException {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<ValidationException> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("ValidationException.message", &f_1)?;
    let ret = ValidationException {
      message: f_1.expect("auto-generated code should have checked for presence of required fields"),
      field: f_2,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("ValidationException");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("message", TType::String, 1))?;
    o_prot.write_string(&self.message)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.field {
      o_prot.write_field_begin(&TFieldIdentifier::new("field", TType::String, 2))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

impl Error for ValidationException {}

impl From<ValidationException> for thrift::Error {
  fn from(e: ValidationException) -> Self {
    thrift::Error::User(Box::new(e))
  }
}

impl Display for ValidationException {
  fn fmt(&self, f: &mut Formatter) -> fmt::Result {
    write!(f, "remote service threw ValidationException")
  }
}

//
// EntPost
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct EntPost {
  pub id: i64,
  pub author_id: i64,
  pub content: String,
  pub media_url: Option<String>,
  pub created_time: i64,
  pub updated_time: Option<i64>,
  pub post_type: String,
  pub visibility: Option<String>,
  pub like_count: i32,
  pub comment_count: i32,
  pub share_count: i32,
  pub tags: Option<String>,
  pub mentions: Option<String>,
}

impl EntPost {
  pub fn new<F4, F6, F8, F12, F13>(id: i64, author_id: i64, content: String, media_url: F4, created_time: i64, updated_time: F6, post_type: String, visibility: F8, like_count: i32, comment_count: i32, share_count: i32, tags: F12, mentions: F13) -> EntPost where F4: Into<Option<String>>, F6: Into<Option<i64>>, F8: Into<Option<String>>, F12: Into<Option<String>>, F13: Into<Option<String>> {
    EntPost {
      id,
      author_id,
      content,
      media_url: media_url.into(),
      created_time,
      updated_time: updated_time.into(),
      post_type,
      visibility: visibility.into(),
      like_count,
      comment_count,
      share_count,
      tags: tags.into(),
      mentions: mentions.into(),
    }
  }
}

impl TSerializable for EntPost {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<EntPost> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<String> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<i64> = None;
    let mut f_7: Option<String> = None;
    let mut f_8: Option<String> = None;
    let mut f_9: Option<i32> = None;
    let mut f_10: Option<i32> = None;
    let mut f_11: Option<i32> = None;
    let mut f_12: Option<String> = None;
    let mut f_13: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_string()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_string()?;
          f_8 = Some(val);
        },
        9 => {
          let val = i_prot.read_i32()?;
          f_9 = Some(val);
        },
        10 => {
          let val = i_prot.read_i32()?;
          f_10 = Some(val);
        },
        11 => {
          let val = i_prot.read_i32()?;
          f_11 = Some(val);
        },
        12 => {
          let val = i_prot.read_string()?;
          f_12 = Some(val);
        },
        13 => {
          let val = i_prot.read_string()?;
          f_13 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("EntPost.id", &f_1)?;
    verify_required_field_exists("EntPost.author_id", &f_2)?;
    verify_required_field_exists("EntPost.content", &f_3)?;
    verify_required_field_exists("EntPost.created_time", &f_5)?;
    verify_required_field_exists("EntPost.post_type", &f_7)?;
    verify_required_field_exists("EntPost.like_count", &f_9)?;
    verify_required_field_exists("EntPost.comment_count", &f_10)?;
    verify_required_field_exists("EntPost.share_count", &f_11)?;
    let ret = EntPost {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      author_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      content: f_3.expect("auto-generated code should have checked for presence of required fields"),
      media_url: f_4,
      created_time: f_5.expect("auto-generated code should have checked for presence of required fields"),
      updated_time: f_6,
      post_type: f_7.expect("auto-generated code should have checked for presence of required fields"),
      visibility: f_8,
      like_count: f_9.expect("auto-generated code should have checked for presence of required fields"),
      comment_count: f_10.expect("auto-generated code should have checked for presence of required fields"),
      share_count: f_11.expect("auto-generated code should have checked for presence of required fields"),
      tags: f_12,
      mentions: f_13,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("EntPost");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("author_id", TType::I64, 2))?;
    o_prot.write_i64(self.author_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("content", TType::String, 3))?;
    o_prot.write_string(&self.content)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.media_url {
      o_prot.write_field_begin(&TFieldIdentifier::new("media_url", TType::String, 4))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("created_time", TType::I64, 5))?;
    o_prot.write_i64(self.created_time)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.updated_time {
      o_prot.write_field_begin(&TFieldIdentifier::new("updated_time", TType::I64, 6))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("post_type", TType::String, 7))?;
    o_prot.write_string(&self.post_type)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.visibility {
      o_prot.write_field_begin(&TFieldIdentifier::new("visibility", TType::String, 8))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("like_count", TType::I32, 9))?;
    o_prot.write_i32(self.like_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("comment_count", TType::I32, 10))?;
    o_prot.write_i32(self.comment_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("share_count", TType::I32, 11))?;
    o_prot.write_i32(self.share_count)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.tags {
      o_prot.write_field_begin(&TFieldIdentifier::new("tags", TType::String, 12))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.mentions {
      o_prot.write_field_begin(&TFieldIdentifier::new("mentions", TType::String, 13))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

