namespace rs tao_database.domains.post

// Generated Thrift definition for EntPost
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

include "../../core/tao.thrift"

// Field validation typedefs
typedef string ENTPOST_CONTENT
typedef string ENTPOST_MEDIA_URL
typedef string ENTPOST_POST_TYPE
typedef string ENTPOST_VISIBILITY

// Validation exception
exception ValidationException {
    1: required string message,
    2: optional string field,
}

struct EntPost {
    1: required i64 id,
    2: required i64 author_id,
    3: required string content,
    4: optional string media_url,
    5: required i64 created_time,
    6: optional i64 updated_time,
    7: required string post_type,
    8: optional string visibility,
    9: required i32 like_count,
    10: required i32 comment_count,
    11: required i32 share_count,
    12: optional string tags,
    13: optional string mentions,
}

// Pure structure definition - no functions allowed in Thrift
// Functions will be generated by codegen and implemented in Rust

