namespace rs tao_database.domains.comment

// Generated Thrift definition for EntComment
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

include "../../core/tao_core.thrift"

// Field validation typedefs
typedef string ENTCOMMENT_CONTENT

// Validation exception
exception ValidationException {
    1: required string message,
    2: optional string field,
}

struct EntComment {
    1: required i64 id,
    2: required i64 author_id,
    3: required i64 post_id,
    4: required string content,
    5: required i64 created_time,
}

// Pure structure definition - no functions allowed in Thrift
// Functions will be generated by codegen and implemented in Rust

