namespace rs tao_database.domains.user

// Generated Thrift definition for EntUser
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

include "../../core/tao_core.thrift"

// Field validation typedefs
typedef string ENTUSER_USERNAME
typedef string ENTUSER_EMAIL
typedef string ENTUSER_FULL_NAME
typedef string ENTUSER_BIO
typedef string ENTUSER_PROFILE_PICTURE_URL
typedef string ENTUSER_LOCATION

// Validation exception
exception ValidationException {
    1: required string message,
    2: optional string field,
}

struct EntUser {
    1: required i64 id,
    2: required string username,
    3: required string email,
    4: required i64 created_time,
    5: optional string full_name,
    6: optional string bio,
    7: optional string profile_picture_url,
    8: optional i64 last_active_time,
    9: required bool is_verified,
    10: optional string location,
    11: optional string privacy_settings,
}

// Pure structure definition - no functions allowed in Thrift
// Functions will be generated by codegen and implemented in Rust

