// Generated Ent trait implementation for EntEvent
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

use std::sync::Arc;
use crate::ent_framework::Entity;
use crate::error::AppResult;
use super::entity::EntEvent;
use crate::infrastructure::tao_core::{TaoOperations, TaoObject};
use crate::infrastructure::tao::Tao;
use thrift::protocol::{TCompactInputProtocol, TSerializable};
use crate::infrastructure::global_tao::get_global_tao;
use std::io::Cursor;
use regex;
use crate::domains::post::EntPost;
use crate::domains::user::EntUser;

impl Entity for EntEvent {
    const ENTITY_TYPE: &'static str = "ent_event";
    
    fn id(&self) -> i64 {
        self.id
    }

    fn validate(&self) -> AppResult<Vec<String>> {
        let mut errors = Vec::new();
        
        // Validate name (required)
        if self.name.trim().is_empty() {
            errors.push("name cannot be empty".to_string());
        }
        
        
        
        Ok(errors)
    }
}

impl EntEvent {
    /// Create an entity from a TaoObject
    pub async fn from_tao_object(tao_obj: TaoObject) -> AppResult<Option<EntEvent>> {
        let tao = get_global_tao()?.clone();
        if tao_obj.otype != EntEvent::ENTITY_TYPE {
            return Ok(None);
        }
        
        let mut cursor = Cursor::new(&tao_obj.data);
        let mut protocol = TCompactInputProtocol::new(&mut cursor);
        let mut entity = EntEvent::read_from_in_protocol(&mut protocol)
            .map_err(|e| crate::error::AppError::SerializationError(e.to_string()))?;
        
        // Update ID from TaoObject
        entity.id = tao_obj.id;
        
        Ok(Some(entity))
    }

    // Edge traversal methods
    
    /// Get attendees via TAO edge traversal
    pub async fn get_attendees(&self) -> AppResult<Vec<EntUser>> {
        let tao = get_global_tao()?.clone();
        let neighbor_ids = tao.get_neighbor_ids(self.id(), "attendees".to_string(), Some(100)).await?;

        let mut results = Vec::new();
        for id in neighbor_ids {
            if let Some(tao_obj) = tao.obj_get(id).await? {
                if let Some(entity) = EntUser::from_tao_object(tao_obj).await? {
                    results.push(entity);
                }
            }
        }
        
        Ok(results)
    }
    
    /// Count attendees via TAO edge traversal
    pub async fn count_attendees(&self) -> AppResult<i64> {
        let tao = get_global_tao()?.clone();
        let count = tao.assoc_count(self.id(), "attendees".to_string()).await?;
        Ok(count as i64)
    }
    
    /// Get related posts via TAO edge traversal
    pub async fn get_related_posts(&self) -> AppResult<Vec<EntPost>> {
        let tao = get_global_tao()?.clone();
        let neighbor_ids = tao.get_neighbor_ids(self.id(), "related_posts".to_string(), Some(100)).await?;

        let mut results = Vec::new();
        for id in neighbor_ids {
            if let Some(tao_obj) = tao.obj_get(id).await? {
                if let Some(entity) = EntPost::from_tao_object(tao_obj).await? {
                    results.push(entity);
                }
            }
        }
        
        Ok(results)
    }
    
    /// Count related posts via TAO edge traversal
    pub async fn count_related_posts(&self) -> AppResult<i64> {
        let tao = get_global_tao()?.clone();
        let count = tao.assoc_count(self.id(), "related_posts".to_string()).await?;
        Ok(count as i64)
    }
    
}

