namespace rs tao_database.domains.event

// Generated Thrift definition for EntEvent
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

include "../../core/tao_core.thrift"

// Field validation typedefs
typedef string ENTEVENT_NAME
typedef string ENTEVENT_DESCRIPTION

// Validation exception
exception ValidationException {
    1: required string message,
    2: optional string field,
}

struct EntEvent {
    1: required i64 id,
    2: required string name,
    3: optional string description,
    4: required i64 event_time,
    5: required i64 created_time,
}

// Pure structure definition - no functions allowed in Thrift
// Functions will be generated by codegen and implemented in Rust

