namespace rs tao_database.domains.page

// Generated Thrift definition for EntPage
// Generated by TAO Ent Framework - DO NOT EDIT
// Regenerate with: cargo run --bin entc generate

include "../../core/tao_core.thrift"

// Field validation typedefs
typedef string ENTPAGE_NAME
typedef string ENTPAGE_DESCRIPTION

// Validation exception
exception ValidationException {
    1: required string message,
    2: optional string field,
}

struct EntPage {
    1: required i64 id,
    2: required string name,
    3: optional string description,
    4: required i64 created_time,
}

// Pure structure definition - no functions allowed in Thrift
// Functions will be generated by codegen and implemented in Rust

