// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

//
// TaoObject
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoObject {
  pub id: i64,
  pub object_type: String,
  pub data: Vec<u8>,
  pub created: i64,
  pub updated: i64,
}

impl TaoObject {
  pub fn new(id: i64, object_type: String, data: Vec<u8>, created: i64, updated: i64) -> TaoObject {
    TaoObject {
      id,
      object_type,
      data,
      created,
      updated,
    }
  }
}

impl TSerializable for TaoObject {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoObject> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<String> = None;
    let mut f_3: Option<Vec<u8>> = None;
    let mut f_4: Option<i64> = None;
    let mut f_5: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_bytes()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoObject.id", &f_1)?;
    verify_required_field_exists("TaoObject.object_type", &f_2)?;
    verify_required_field_exists("TaoObject.data", &f_3)?;
    verify_required_field_exists("TaoObject.created", &f_4)?;
    verify_required_field_exists("TaoObject.updated", &f_5)?;
    let ret = TaoObject {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      object_type: f_2.expect("auto-generated code should have checked for presence of required fields"),
      data: f_3.expect("auto-generated code should have checked for presence of required fields"),
      created: f_4.expect("auto-generated code should have checked for presence of required fields"),
      updated: f_5.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoObject");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("object_type", TType::String, 2))?;
    o_prot.write_string(&self.object_type)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("data", TType::String, 3))?;
    o_prot.write_bytes(&self.data)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("created", TType::I64, 4))?;
    o_prot.write_i64(self.created)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("updated", TType::I64, 5))?;
    o_prot.write_i64(self.updated)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TaoAssociation
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoAssociation {
  pub edge_id: i64,
  pub source_id: i64,
  pub target_id: i64,
  pub association_type: String,
  pub association_data: Option<Vec<u8>>,
  pub created: i64,
  pub updated: i64,
  pub time_field: i64,
}

impl TaoAssociation {
  pub fn new<F5>(edge_id: i64, source_id: i64, target_id: i64, association_type: String, association_data: F5, created: i64, updated: i64, time_field: i64) -> TaoAssociation where F5: Into<Option<Vec<u8>>> {
    TaoAssociation {
      edge_id,
      source_id,
      target_id,
      association_type,
      association_data: association_data.into(),
      created,
      updated,
      time_field,
    }
  }
}

impl TSerializable for TaoAssociation {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoAssociation> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<Vec<u8>> = None;
    let mut f_6: Option<i64> = None;
    let mut f_7: Option<i64> = None;
    let mut f_8: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_bytes()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i64()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_i64()?;
          f_8 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoAssociation.edge_id", &f_1)?;
    verify_required_field_exists("TaoAssociation.source_id", &f_2)?;
    verify_required_field_exists("TaoAssociation.target_id", &f_3)?;
    verify_required_field_exists("TaoAssociation.association_type", &f_4)?;
    verify_required_field_exists("TaoAssociation.created", &f_6)?;
    verify_required_field_exists("TaoAssociation.updated", &f_7)?;
    verify_required_field_exists("TaoAssociation.time_field", &f_8)?;
    let ret = TaoAssociation {
      edge_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      source_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      target_id: f_3.expect("auto-generated code should have checked for presence of required fields"),
      association_type: f_4.expect("auto-generated code should have checked for presence of required fields"),
      association_data: f_5,
      created: f_6.expect("auto-generated code should have checked for presence of required fields"),
      updated: f_7.expect("auto-generated code should have checked for presence of required fields"),
      time_field: f_8.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoAssociation");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("edge_id", TType::I64, 1))?;
    o_prot.write_i64(self.edge_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("source_id", TType::I64, 2))?;
    o_prot.write_i64(self.source_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("target_id", TType::I64, 3))?;
    o_prot.write_i64(self.target_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("association_type", TType::String, 4))?;
    o_prot.write_string(&self.association_type)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.association_data {
      o_prot.write_field_begin(&TFieldIdentifier::new("association_data", TType::String, 5))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("created", TType::I64, 6))?;
    o_prot.write_i64(self.created)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("updated", TType::I64, 7))?;
    o_prot.write_i64(self.updated)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("time_field", TType::I64, 8))?;
    o_prot.write_i64(self.time_field)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TaoIndex
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoIndex {
  pub entity_id: i64,
  pub edge_id: i64,
  pub target_entity_id: i64,
  pub association_type: String,
  pub created: i64,
  pub updated: i64,
}

impl TaoIndex {
  pub fn new(entity_id: i64, edge_id: i64, target_entity_id: i64, association_type: String, created: i64, updated: i64) -> TaoIndex {
    TaoIndex {
      entity_id,
      edge_id,
      target_entity_id,
      association_type,
      created,
      updated,
    }
  }
}

impl TSerializable for TaoIndex {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoIndex> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoIndex.entity_id", &f_1)?;
    verify_required_field_exists("TaoIndex.edge_id", &f_2)?;
    verify_required_field_exists("TaoIndex.target_entity_id", &f_3)?;
    verify_required_field_exists("TaoIndex.association_type", &f_4)?;
    verify_required_field_exists("TaoIndex.created", &f_5)?;
    verify_required_field_exists("TaoIndex.updated", &f_6)?;
    let ret = TaoIndex {
      entity_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      edge_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      target_entity_id: f_3.expect("auto-generated code should have checked for presence of required fields"),
      association_type: f_4.expect("auto-generated code should have checked for presence of required fields"),
      created: f_5.expect("auto-generated code should have checked for presence of required fields"),
      updated: f_6.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoIndex");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("entity_id", TType::I64, 1))?;
    o_prot.write_i64(self.entity_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("edge_id", TType::I64, 2))?;
    o_prot.write_i64(self.edge_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("target_entity_id", TType::I64, 3))?;
    o_prot.write_i64(self.target_entity_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("association_type", TType::String, 4))?;
    o_prot.write_string(&self.association_type)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("created", TType::I64, 5))?;
    o_prot.write_i64(self.created)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("updated", TType::I64, 6))?;
    o_prot.write_i64(self.updated)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TaoAssociationQuery
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoAssociationQuery {
  pub id1: i64,
  pub id2: Option<i64>,
  pub assoc_type: String,
  pub start_time: Option<i64>,
  pub end_time: Option<i64>,
  pub limit: Option<i32>,
  pub offset: Option<i64>,
}

impl TaoAssociationQuery {
  pub fn new<F2, F4, F5, F6, F7>(id1: i64, id2: F2, assoc_type: String, start_time: F4, end_time: F5, limit: F6, offset: F7) -> TaoAssociationQuery where F2: Into<Option<i64>>, F4: Into<Option<i64>>, F5: Into<Option<i64>>, F6: Into<Option<i32>>, F7: Into<Option<i64>> {
    TaoAssociationQuery {
      id1,
      id2: id2.into(),
      assoc_type,
      start_time: start_time.into(),
      end_time: end_time.into(),
      limit: limit.into(),
      offset: offset.into(),
    }
  }
}

impl TSerializable for TaoAssociationQuery {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoAssociationQuery> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<String> = None;
    let mut f_4: Option<i64> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<i32> = None;
    let mut f_7: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i32()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i64()?;
          f_7 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoAssociationQuery.id1", &f_1)?;
    verify_required_field_exists("TaoAssociationQuery.assoc_type", &f_3)?;
    let ret = TaoAssociationQuery {
      id1: f_1.expect("auto-generated code should have checked for presence of required fields"),
      id2: f_2,
      assoc_type: f_3.expect("auto-generated code should have checked for presence of required fields"),
      start_time: f_4,
      end_time: f_5,
      limit: f_6,
      offset: f_7,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoAssociationQuery");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id1", TType::I64, 1))?;
    o_prot.write_i64(self.id1)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.id2 {
      o_prot.write_field_begin(&TFieldIdentifier::new("id2", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("assoc_type", TType::String, 3))?;
    o_prot.write_string(&self.assoc_type)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.start_time {
      o_prot.write_field_begin(&TFieldIdentifier::new("start_time", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.end_time {
      o_prot.write_field_begin(&TFieldIdentifier::new("end_time", TType::I64, 5))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.limit {
      o_prot.write_field_begin(&TFieldIdentifier::new("limit", TType::I32, 6))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.offset {
      o_prot.write_field_begin(&TFieldIdentifier::new("offset", TType::I64, 7))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TaoBatchObjectRequest
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoBatchObjectRequest {
  pub object_ids: Vec<i64>,
  pub object_type: String,
}

impl TaoBatchObjectRequest {
  pub fn new(object_ids: Vec<i64>, object_type: String) -> TaoBatchObjectRequest {
    TaoBatchObjectRequest {
      object_ids,
      object_type,
    }
  }
}

impl TSerializable for TaoBatchObjectRequest {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoBatchObjectRequest> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<i64>> = None;
    let mut f_2: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<i64> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = i_prot.read_i64()?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoBatchObjectRequest.object_ids", &f_1)?;
    verify_required_field_exists("TaoBatchObjectRequest.object_type", &f_2)?;
    let ret = TaoBatchObjectRequest {
      object_ids: f_1.expect("auto-generated code should have checked for presence of required fields"),
      object_type: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoBatchObjectRequest");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("object_ids", TType::List, 1))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::I64, self.object_ids.len() as i32))?;
    for e in &self.object_ids {
      o_prot.write_i64(*e)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("object_type", TType::String, 2))?;
    o_prot.write_string(&self.object_type)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TaoBatchAssociationRequest
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TaoBatchAssociationRequest {
  pub queries: Vec<TaoAssociationQuery>,
}

impl TaoBatchAssociationRequest {
  pub fn new(queries: Vec<TaoAssociationQuery>) -> TaoBatchAssociationRequest {
    TaoBatchAssociationRequest {
      queries,
    }
  }
}

impl TSerializable for TaoBatchAssociationRequest {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TaoBatchAssociationRequest> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<TaoAssociationQuery>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<TaoAssociationQuery> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_1 = TaoAssociationQuery::read_from_in_protocol(i_prot)?;
            val.push(list_elem_1);
          }
          i_prot.read_list_end()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TaoBatchAssociationRequest.queries", &f_1)?;
    let ret = TaoBatchAssociationRequest {
      queries: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TaoBatchAssociationRequest");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("queries", TType::List, 1))?;
    o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, self.queries.len() as i32))?;
    for e in &self.queries {
      e.write_to_out_protocol(o_prot)?;
    }
    o_prot.write_list_end()?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

